name = "Parallax Bonanza"
license = "Apache License 2.0"
licenselink = "//github.com/xblackbytesx/hugo-parallax-bonanza/blob/master/LICENSE"
description = "A one page HTML theme with crazy parallaxes."
homepage = "//github.com/xblackbytesx/hugo-parallax-bonanza"
tags = ["creative", "portfolio"]
features = ["responsive", "portfolio", "substitutable strings"]
min_version = 0.14

[author]
  name = "Fabio Bier"
  homepage = "//github.com/xblackbytesx"

# If porting an existing theme
[original]
  name = "digitalcraftsman"
  homepage = "//github.com/digitalcraftsman/hugo-creative-theme"
  repo = "//github.com/digitalcraftsman/hugo-creative-theme"
